
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mysql-radondb-com-v1alpha1-mysqlcluster
  failurePolicy: Fail
  name: vmysqlcluster.kb.io
  rules:
  - apiGroups:
    - mysql.radondb.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mysqlclusters
  sideEffects: None
