apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  node.cnf: |-
{{ .Files.Get "files/node.cnf" | indent 4 }}
  server-id.cnf: |
    [mysqld]
    server-id=@@SERVER_ID@@
  create-peers.sh: |
    #!/bin/bash
    i=0
    while [ $i -lt {{ .Values.replicaCount }} ]
    do
      if [ $i = 0 ]
      then
        echo -n "{{ template "fullname" . }}-${i}.{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8801"
      else
        echo -n ",{{ template "fullname" . }}-${i}.{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8801"
      fi
      let i++
    done

