# permissions for end users to view mysqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlcluster-viewer-role
rules:
- apiGroups:
  - mysql.radondb.com
  resources:
  - mysqlclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.radondb.com
  resources:
  - mysqlclusters/status
  verbs:
  - get
