---
apiVersion: v1
kind: Secret
metadata:
  # Corresponding to the user's secretName
  name: sample-user-password
data:
  # The key corresponding to the user's secretKey
  # RadonDB@123
  superUser: UmFkb25EQkAxMjM=
  normalUser: UmFkb25EQkAxMjM=
---
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlUser
metadata:
  name: super-user
spec:
  ## MySQL user name.
  user: super_user
  withGrantOption: true
  tlsOptions: 
    type: NONE
  hosts: 
    - "%"
  permissions:
    - database: "*"
      tables:
        - "*"
      privileges:
        - ALL
  ## Specify the cluster where the user is located.
  userOwner:
    clusterName: sample
    nameSpace: default
  ## Specify the secret object for user.
  secretSelector:
    secretName: sample-user-password
    secretKey: superUser
---
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlUser
metadata:
  name: normal-user
spec:
  ## MySQL user name.
  user: normal_user
  withGrantOption: false
  tlsOptions: 
    type: NONE
  hosts: 
    - "%"
  permissions:
    - database: "*"
      tables:
        - "*"
      privileges:
        - USAGE
  ## Specify the cluster where the user is located.
  userOwner:
    clusterName: sample
    nameSpace: default
  ## Specify the secret object for user.
  secretSelector:
    secretName: sample-user-password
    secretKey: normalUser
