apiVersion: v1
kind: Secret
metadata:
  # Corresponding to the user's secretName
  name: sample-user-password
data:
  # The key corresponding to the user's secretKey
  # RadonDB@123
  pwdForSample: UmFkb25EQkAxMjM=
  # A secret may store many passwords like this, so different keys are needed to distinguish
  # pwdForSample2:
  # pwdForSample3:
