apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: radondb-nfs-hostpath
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radondb-nfs-pv
  labels:
    type: local
spec:
  storageClassName: radondb-nfs-hostpath
  # you can set affinity ,for example:
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - node2
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/radondb-nfs-backup"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radondb-nfs-pvc
spec:
  storageClassName: radondb-nfs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
