apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql-operator.fullname" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    chart: {{ template "mysql-operator.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "mysql-operator.name" . }}
      release: {{ .Release.Name | quote }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "mysql-operator.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      {{- if .Values.rbacProxy.create }}
      - name: kube-rbac-proxy
        image: {{ .Values.rbacProxy.image }}
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
      {{- end }}
      - name: manager
        command:
        - /manager
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        image: "{{ .Values.manager.image }}:{{ .Values.manager.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{ toYaml .Values.manager.resources | indent 10 }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
