name: Code check

on:   
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/**
      - charts/**
      - config/**
      - docs/**
      - hack/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - .github/**
      - charts/**
      - config/**
      - docs/**
      - hack/**

jobs:

  fmtvet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Run go fmt/vet
      run: |
        make fmt
        make vet

    - name: Check
      run: d="$(git status -s)" && if [ -n "$d" ]; then echo "check-crd error:" ; echo "$d"; exit 1; fi 

  checkcrd:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Recreate crd
      run: |
        make manifests
        make generate

    - name: Check crd
      run: d="$(git status -s)" && if [ -n "$d" ]; then echo "check-crd error:" ; echo "$d"; exit 1; fi 

  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2020.2.1

    - name: Run staticcheck
      run: staticcheck -f stylish ./... 

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Make build
      run: make build
