name: Publish images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'images tag'
        required: true 
        type: string
      build_operator:
        description: ""
        required: true
        default: true
        type: boolean
      build_sidecar:
        description: ""
        required: true
        default: true
        type: boolean

jobs:
  build_operator:
    uses: zhl003/radondb-mysql-kubernetes/.github/workflows/build_operator_image.yml@support_arm_platform
    if: ${{ github.event.inputs.build_operator }}
    with:
      image_tag: ${{ github.event.inputs.tag }}
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_sidecar:
    uses: zhl003/radondb-mysql-kubernetes/.github/workflows/build_sidecar_image.yml@support_arm_platform
    if: ${{ github.event.inputs.build_sidecar }}
    with:
      image_tag: ${{ github.event.inputs.tag }} 
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
