name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: false 
        type: string

jobs: 
  update_release_draft:
    uses: ./.github/workflows/release_drafter.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}
  
  build_operator:
    uses: ./.github/workflows/build_operator_image.yml
    needs: update_release_draft
    with:
      image_tag: ${{ needs.update_release_draft.outputs.version }}
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_sidecar:
    uses: ./.github/workflows/build_sidecar_image.yml
    needs: update_release_draft
    with:
      image_tag: ${{ needs.update_release_draft.outputs.version }} 
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_xenon:
    uses: ./.github/workflows/build_xenon_image.yml
    needs: update_release_draft
    with:
      image_tag: ${{ needs.update_release_draft.outputs.version }} 
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  publish_chart:
    uses: ./.github/workflows/publish_charts.yml
    if: ${{ github.event.inputs.version == '' }}
    needs: update_release_draft
    with:
      version: ${{ needs.update_release_draft.outputs.version }}
      upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
