name: Publish Charts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Packaging the chart
        run: helm package ./charts/mysql-operator/

      - uses: actions/upload-artifact@v2
        with:
          name: mysql-operator-chart
          path: ./mysql-operator-*.tgz
          retention-days: 1

  publish:
    name: Publish charts on GitHub Pages
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: operator-charts

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - uses: actions/download-artifact@v2
        with:
          name: mysql-operator-chart

      - name: Update charts index
        run: |
          helm repo index --url https://radondb.github.io/radondb-mysql-kubernetes/ --merge index.yaml .
          git add .

      - name: Check diffs
        run: |
          diffs=$(git status -s)
          if [ "$diffs" = "" ]; then
            echo "NO_DIFF=1" >> $GITHUB_ENV
          else
            printf "%s\n" "$diffs"
          fi

      - name: Commit and push
        if: env.NO_DIFF != '1'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update chart repo

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: operator-charts
