name: Publish images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'images tag'
        required: true 
        type: string
      build_operator:
        description: ""
        required: true
        default: true
        type: boolean
      build_sidecar:
        description: ""
        required: true
        default: true
        type: boolean
      build_xenon:
        description: ""
        required: true
        default: true
        type: boolean

jobs:
  build_operator:
    uses: radondb/radondb-mysql-kubernetes/.github/workflows/build_operator_image.yml@main
    if: ${{ github.event.inputs.build_operator == 'true' }}
    with:
      image_tag: ${{ github.event.inputs.tag }}
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_sidecar:
    uses: radondb/radondb-mysql-kubernetes/.github/workflows/build_sidecar_image.yml@main
    if: ${{ github.event.inputs.build_sidecar == 'true' }}
    with:
      image_tag: ${{ github.event.inputs.tag }} 
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_xenon:
    uses: radondb/radondb-mysql-kubernetes/.github/workflows/build_xenon_image.yml@main
    if: ${{ github.event.inputs.build_xenon == 'true' }}
    with:
      image_tag: ${{ github.event.inputs.tag }} 
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
