name: Publish Charts

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      upload_url:
        required: true 
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Modify chart version
        id: chart_version
        run: |
          input=${{ inputs.version }}
          chart_version=${input#*v}
          echo "::set-output name=asset_name::mysql-operator-$chart_version.tgz"
          sed -i "/^version:*/cversion: $chart_version" ./charts/mysql-operator/Chart.yaml

      - name: Modify appVersion
        run: |
          sed -i '/^appVersion:*/cappVersion: ${{ inputs.version }}' ./charts/mysql-operator/Chart.yaml

      - name: Modify operator image tag
        run: |
          sed -i '/^  tag:*/c\  tag: ${{ inputs.version }}' charts/mysql-operator/values.yaml

      - name: Packaging the chart
        run: helm package ./charts/mysql-operator/

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }} 
          asset_path: ./${{ steps.chart_version.outputs.asset_name }}
          asset_name: ${{ steps.chart_version.outputs.asset_name }}
          asset_content_type: application/gzip

      - uses: actions/upload-artifact@v2
        with:
          name: mysql-operator-chart
          path: ./${{ steps.chart_version.outputs.asset_name }}
          retention-days: 1

  publish:
    name: Publish charts on GitHub Pages
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: operator-charts

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - uses: actions/download-artifact@v2
        with:
          name: mysql-operator-chart

      - name: Update charts index
        run: |
          helm repo index --url https://radondb.github.io/radondb-mysql-kubernetes/ --merge index.yaml .
          git add .

      - name: Check diffs
        run: |
          diffs=$(git status -s)
          if [ "$diffs" = "" ]; then
            echo "NO_DIFF=1" >> $GITHUB_ENV
          else
            printf "%s\n" "$diffs"
          fi

      - name: Commit and push
        if: env.NO_DIFF != '1'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update chart repo

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: operator-charts
