name: Publish release

on:
  workflow_dispatch:

jobs: 
    update_release_draft:
      uses: radondb/radondb-mysql-kubernetes/.github/workflows/release_drafter.yml@main
      secrets:
        git_token: ${{ secrets.GITHUB_TOKEN }}
    
    build_operator:
      uses: radondb/radondb-mysql-kubernetes/.github/workflows/build_operator_image.yml@main
      needs: update_release_draft
      with:
        image_tag: ${{ needs.update_release_draft.outputs.version }}
      secrets: 
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    build_sidecar:
      uses: radondb/radondb-mysql-kubernetes/.github/workflows/build_sidecar_image.yml@main
      needs: update_release_draft
      with:
        image_tag: ${{ needs.update_release_draft.outputs.version }} 
      secrets: 
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    publish_chart:
      uses: radondb/radondb-mysql-kubernetes/.github/workflows/publish_charts.yml@main
      needs: update_release_draft
      with:
        version: ${{ needs.update_release_draft.outputs.version }}

